-- BANKA tablosu
CREATE TABLE BANKA (
  Kod INT PRIMARY KEY,
  Ad NVARCHAR(50) NOT NULL,
  Telefon NVARCHAR(20) NOT NULL
);

-- MÜŞTERİ tablosu
CREATE TABLE MUSTERİ (
  TCNo NVARCHAR(11) PRIMARY KEY,
  Ad NVARCHAR(50) NOT NULL,
  Soyad NVARCHAR(50) NOT NULL,
  DogumTarihi DATE NOT NULL,
  Telefon NVARCHAR(20) NOT NULL,
  Eposta NVARCHAR(50) NOT NULL
);

-- İŞLEM tablosu
CREATE TABLE İSLEM (
  İslemNo INT PRIMARY KEY,
  TCNo NVARCHAR(11) NOT NULL,
  Bakiye DECIMAL(10, 2) NOT NULL,
  İslemTarihi DATETIME NOT NULL,
  İslemTuru NVARCHAR(50) NOT NULL,
  Tutar DECIMAL(10, 2) NOT NULL,
  FOREIGN KEY (TCNo) REFERENCES MUSTERİ(TCNo)
);

-- BANKA ÇALIŞANI tablosu
CREATE TABLE BANKACALİSANİ (
  TCNo NVARCHAR(11) PRIMARY KEY,
  Ad NVARCHAR(50) NOT NULL,
  Soyad NVARCHAR(50) NOT NULL,
  Pozisyon NVARCHAR(50) NOT NULL
);

-- ŞUBE tablosu
CREATE TABLE SUBE (
  SubeNo INT PRIMARY KEY,
  SubeAdres NVARCHAR(100) NOT NULL,
  SubeTelefon NVARCHAR(20) NOT NULL
);

-- KREDİ tablosu
CREATE TABLE KREDİ (
  KrediNo INT PRIMARY KEY,
  KrediTuru NVARCHAR(50) NOT NULL,
  KrediMiktar DECIMAL(10, 2) NOT NULL,
  FaizOran DECIMAL(5, 2) NOT NULL
);

-- HESAP tablosu
CREATE TABLE HESAP (
  HesapNo INT PRIMARY KEY,
  Bakiye DECIMAL(10, 2) NOT NULL,
  Tur NVARCHAR(50) NOT NULL
);